### ISSUE TITLE
is not compatible with Android S and above

### ISSUE THREAD

**Issue by almendezl** [Aashishm178/mobile_number_picker#6]
`Failed to handle method call
E/MethodChannel#mobile_number(10043): java.lang.IllegalArgumentException: com.example.project_flutter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MethodChannel#mobile_number(10043): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MethodChannel#mobile_number(10043): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
E/MethodChannel#mobile_number(10043): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:487)
E/MethodChannel#mobile_number(10043): 	at android.app.PendingIntent.getActivity(PendingIntent.java:473)
E/MethodChannel#mobile_number(10043): 	at android.app.PendingIntent.getActivity(PendingIntent.java:437)
E/MethodChannel#mobile_number(10043): 	at com.google.android.gms.internal.auth-api.zzr.zzc(com.google.android.gms:play-services-auth@@19.0.0:19)
E/MethodChannel#mobile_number(10043): 	at com.google.android.gms.internal.auth-api.zzj.getHintPickerIntent(com.google.android.gms:play-services-auth@@19.0.0:13)
E/MethodChannel#mobile_number(10043): 	at com.neratech.mobile_number_picker.MobileNumberPickerPlugin.getHintPhoneNumber(MobileNumberPickerPlugin.java:60)
E/MethodChannel#mobile_number(10043): 	at com.neratech.mobile_number_picker.MobileNumberPickerPlugin.onMethodCall(MobileNumberPickerPlugin.java:47)
E/MethodChannel#mobile_number(10043): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#mobile_number(10043): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#mobile_number(10043): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#mobile_number(10043): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#mobile_number(10043): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#mobile_number(10043): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#mobile_number(10043): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#mobile_number(10043): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#mobile_number(10043): 	at android.app.ActivityThread.main(ActivityThread.java:8116)
E/MethodChannel#mobile_number(10043): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#mobile_number(10043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/MethodChannel#mobile_number(10043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/flutter (10043): PlatformException(error, com.example.project_flutter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

**Comment by prateek-aher** [comment]
@almendezl This makes sense now. On initiating the method channel from the package, my app crashed and this appeared in the debug console:

`E/AndroidRuntime(15319): FATAL EXCEPTION: main
E/AndroidRuntime(15319): Process: com.example.app, PID: 15319
E/AndroidRuntime(15319): java.lang.NoSuchFieldError: No static field CREDENTIALS_API of type Lcom/google/android/gms/common/api/Api; in class Lcom/google/android/gms/auth/api/Auth; or its superclasses (declaration of 'com.google.android.gms.auth.api.Auth' appears in /data/app/~~ZNQTxbV92-p0DMeKXbHIsw==/consumer.rapsap.com-2Lid_GmRSJ5k43tyvuJRWw==/base.apk)
E/AndroidRuntime(15319): 	at com.neratech.mobile_number_picker.MobileNumberPickerPlugin.onMethodCall(MobileNumberPickerPlugin.java:42)
E/AndroidRuntime(15319): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(15319): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(15319): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(15319): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(15319): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(15319): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15319): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(15319): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(15319): 	at android.app.ActivityThread.main(ActivityThread.java:8377)
E/AndroidRuntime(15319): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15319): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(15319): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
I/Process (15319): Sending signal. PID: 15319 SIG: 9
Lost connection to device.

Exited.
`
